Fix github action SRP-check

diff --git a/.github/workflows/haskell.yml b/.github/workflows/haskell.yml
--- a/.github/workflows/haskell.yml
+++ b/.github/workflows/haskell.yml
@@ -496,11 +496,16 @@ jobs:
     - name: Check if provided formal-ledger-specifications SRP commit hash exists
       run: |
         TAG=$(sed -ne \
-          '/ *location: *https:\/\/github.com\/IntersectMBO\/formal-ledger-specifications.git/,/--sha256/ p' \
+          '/ *location: *https:\/\/github.com\/IntersectMBO\/formal-ledger-specifications.git/,/tag:/ p' \
           cabal.project \
         | sed -ne 's/^ *tag: *//p')
+        if [ -z "$TAG" ]; then
+          echo "Error: IntersectMBO/formal-ledger-specifications SRP tag not found."
+          exit 1
+        fi
         git fetch https://github.com/intersectmbo/formal-ledger-specifications.git MAlonzo-code
-        git show -s $TAG || { \
+
+        git show -s "$TAG" || { \
           echo "Commit $TAG was not found on the MAlonzo-code branch of formal-ledger-specifications."
           exit 1
         }
